version: "3.8"
services:
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/backend
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    networks:
      - localnet
    depends_on:
      - store_mysql
    stdin_open: true
    tty: true

  store_client:
    container_name: store_client
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3001:80"
    depends_on:
      - backend
    # ports:
    #   - "443:443" # Map HTTPS port
    #   - "80:80" # Redirect HTTP to HTTPS
    # volumes:
    #   - ./127.0.0.1-key.pem:/frontend/127.0.0.1-key.pem
    #   - ./127.0.0.1.pem:/frontend/127.0.0.1.pem # Mount SSL certificates

    env_file:
      - ./.env
    restart: always
    networks:
      - localnet
  store_admin:
    container_name: store_admin
    build:
      context: ./admin
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    # ports:
    #   - "443:443" # Map HTTPS port
    #   - "80:80" # Redirect HTTP to HTTPS
    # volumes:
    #   - ./127.0.0.1-key.pem:/frontend/127.0.0.1-key.pem
    #   - ./127.0.0.1.pem:/frontend/127.0.0.1.pem # Mount SSL certificates

    env_file:
      - ./.env
    restart: always
    networks:
      - localnet

  store_mysql:
    image: mysql:8.0
    container_name: store_mysql
    ports:
      - "3310:3310"
    env_file:
      - ./.env
    command:
      - mysqld
      - --port=3310
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
      - store_mysql_data:/var/lib/mysql
    restart: always

    networks:
      - localnet

networks:
  localnet:
    driver: bridge

volumes:
  store_mysql_data:
